# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_channel_google_analytics_create:
    pattern: /channel/google-analytics/create
    defaults: { _controller: CampaignChainChannelGoogleAnalyticsBundle:GoogleAnalytics:create }
    

campaignchain_channel_google_analytics_login:
    pattern: /channel/google-analytics/login
    defaults: { _controller: CampaignChainChannelGoogleAnalyticsBundle:GoogleAnalytics:login }


campaignchain_channel_google_analytics_list_properties:
    pattern: /channel/google-analytics/properties
    defaults: { _controller: CampaignChainChannelGoogleAnalyticsBundle:GoogleAnalytics:listProperties }


campaignchain_channel_google_analytics_connect_location:
    pattern: /channel/google-analytics/connect
    defaults: { _controller: CampaignChainChannelGoogleAnalyticsBundle:GoogleAnalytics:createLocation }


