# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.channel.google_analytics.rest_client:
        class: CampaignChain\Channel\GoogleAnalyticsBundle\Service\RestClient
        arguments:
            - "@campaignchain.core.location"
            - "@campaignchain.security.authentication.client.oauth.application"
            - "@campaignchain.security.authentication.client.oauth.token"